Repository ITA-Dnipro/Dp-197-Kony-Team-Alexander, pull requests merged in 2021-03, with the labels that each got.

#104 Novikov 93 create favourite list service
  controllers/mobile/frmFavouriteListController/frmFavouriteListController.js
  controllers/mobile/frmMovieDetailsController/frmMovieDetailsController.js
  controllers/mobile/frmSearchController/frmSearchController.js
  mobileFabricServiceConfigMap.json
  modules/DB.js
  modules/require/AuthenticationService.js
  modules/require/FakeAuthServiceImpl.js
  modules/require/FavouriteListService.js
Labels: ready for code review

#109 Novikov 106 create user profile service
  controllers/mobile/Form1Controller/Form1Controller.js
  controllers/mobile/frmProfileController/frmProfileController.js
  forms/mobile/Form1.sm/Form1.json
  forms/mobile/frmFavouriteList.sm/btnBack.json
  forms/mobile/frmFavouriteList.sm/lblHeader.json
  forms/mobile/frmMovieList.sm/HeaderControl.json
  forms/mobile/frmMovieList.sm/btnSearch.json
  forms/mobile/frmProfile.sm/BackHeader.json
  forms/mobile/frmProfile.sm/btnBackToMovieList.json
  forms/mobile/frmProfile.sm/btnProfileFormChange.json
  forms/mobile/frmProfile.sm/frmProfile.json
  forms/mobile/frmProfile.sm/inpProfileLogin.json
  forms/mobile/frmProfile.sm/inpProfileName.json
  mobileFabricServiceConfigMap.json
  modules/require/AuthServiceFabricImpl.js
  modules/require/MovieService.js
  modules/require/UserProfileService.js
  themes/defaultTheme/sknBtnBack.json
  themes/defaultTheme/sknBtnDropdown.json
  themes/defaultTheme/sknBtnFavouriteHeader.json
  themes/defaultTheme/sknBtnFocusBack.json
  themes/defaultTheme/sknBtnFocusFavouriteHeader.json
  themes/defaultTheme/sknInpAuth.json
  themes/defaultTheme/sknInpFocusAuth.json
  themes/defaultTheme/sknbtnBackHeader.json
  themes/defaultTheme/sknbtnBackHeaderFocus.json
  userwidgets/com.ita.components.BackHeader/userwidgetmodel.sm/btnBackHeader.json
  userwidgets/com.ita.components.HeaderControl/modules/require/HeaderControlController.js
  userwidgets/com.ita.components.HeaderControl/userwidgetmodel.sm/btnBack.json
  userwidgets/com.ita.components.HeaderControl/userwidgetmodel.sm/lblCaption.json
Labels: ready for code review, ready for form review

#111 Rakhimova 101 fabric impl for new services
  controllers/mobile/frmMovieDetailsController/frmMovieDetailsController.js
  controllers/mobile/frmPersonInfoController/frmPersonInfoController.js
  forms/mobile/frmMovieDetails.sm/flxCreatedBy.json
  forms/mobile/frmMovieDetails.sm/flxCreatedByContainer.json
  forms/mobile/frmMovieDetails.sm/flxDirectorContainer.json
  forms/mobile/frmMovieDetails.sm/flxDirectorInfo.json
  forms/mobile/frmMovieDetails.sm/flxMovieDetails.json
  forms/mobile/frmMovieDetails.sm/flxTvDetails.json
  forms/mobile/frmMovieDetails.sm/lblCountry.json
  forms/mobile/frmMovieDetails.sm/lblCreatedBy.json
  forms/mobile/frmMovieDetails.sm/lblDirector.json
  forms/mobile/frmPersonInfo.sm/lblName.json
  modules/MovieData.js
  modules/TvData.js
  modules/require/AuthenticationService.js
  modules/require/MovieService.js
  modules/require/MovieServiceFabricImpl.js
  modules/require/MovieServiceHttpImpl.js
Labels: ready for code review

#115 Rakhimova 96 search for tv shows
  controllers/mobile/frmProfileController/frmProfileController.js
  controllers/mobile/frmSearchController/frmSearchController.js
  forms/mobile/frmSearch.sm/btnMovies.json
  forms/mobile/frmSearch.sm/btnPeople.json
  forms/mobile/frmSearch.sm/btnTVShows.json
  forms/mobile/frmSearch.sm/flxBtnContainer.json
  forms/mobile/frmSearch.sm/frmSearch.json
  forms/mobile/frmSearch.sm/lblNotFound.json
  forms/mobile/frmSearch.sm/lstMovies.json
  mobileFabricServiceConfigMap.json
  modules/TvData.js
  modules/require/MovieService.js
  modules/require/MovieServiceFabricImpl.js
Labels: ready for code review, ready for form review

#117 Rakhimova 114 genre list in module
  controllers/mobile/frmMovieDetailsController/frmMovieDetailsController.js
  controllers/mobile/frmMovieListController/frmMovieListController.js
  controllers/mobile/frmPersonInfoController/frmPersonInfoController.js
  controllers/mobile/frmSearchController/frmSearchController.js
  forms/mobile/frmMovieDetails.sm/btnBack.json
  forms/mobile/frmMovieDetails.sm/cmpHeader.json
  forms/mobile/frmMovieDetails.sm/flxHeader.json
  forms/mobile/frmMovieDetails.sm/flxMainScroll.json
  forms/mobile/frmMovieDetails.sm/flxMovieDetailsHeader.json
  forms/mobile/frmMovieDetails.sm/frmMovieDetails.json
  forms/mobile/frmMovieDetails.sm/lblCountry.json
  forms/mobile/frmMovieDetails.sm/lblCountryInfo.json
  forms/mobile/frmPersonInfo.sm/btnBack.json
  forms/mobile/frmPersonInfo.sm/btnSearch.json
  forms/mobile/frmPersonInfo.sm/cmpHeader.json
  forms/mobile/frmPersonInfo.sm/flxHeader.json
  forms/mobile/frmPersonInfo.sm/flxMainScroll.json
  forms/mobile/frmPersonInfo.sm/frmPersonInfo.json
  mobileFabricServiceConfigMap.json
  modules/generalFunctions.js
  modules/require/MovieService.js
  modules/require/MovieServiceFabricImpl.js
  studioactions/mobile/AS_Form_a234907cc68042b18f0e3005d909af2d.js
  studioactions/mobile/AS_Form_a4d153b60e3b4599b2d610533daba1da.js
  studioactions/mobile/AS_Form_a4fe167533d44ce3b3e90334979dcc63.js
  studioactions/mobile/AS_Form_ab3c9d6bf79342b5914e98a1a2ebb1a6.js
  studioactions/mobile/AS_Form_b58272d7037249e39a72aed17f1f3a44.js
  studioactions/mobile/AS_Form_b607240b2410432ab9641bacf35a9afc.js
  studioactions/mobile/AS_Form_bd49d60ff33a4c2e815fb173d6506ee1.js
  studioactions/mobile/AS_Form_c1dc4ef43ec845188c686560b5b1d55e.js
  studioactions/mobile/AS_Form_c2966ac0833442e28ee6a6ef800bd0c6.js
  studioactions/mobile/AS_Form_cc0b999171484da28a53aecb743d9108.js
  studioactions/mobile/AS_Form_d4c44e487b664d158bb64d31b299eda3.js
  studioactions/mobile/AS_Form_d4cfa8ef34744088a2a77ca1afd3809a.js
  studioactions/mobile/AS_Form_da0e4c479b214f66bb062f7cda283235.js
  studioactions/mobile/AS_Form_e0142d64be7645b38a25616bc27c1287.js
  studioactions/mobile/AS_Form_f024f4c5388d46aea0d9dea249354cff.js
  studioactions/mobile/AS_Form_ge26ef28ecbe4046b34b5d9640dd91bb.js
  studioactions/mobile/AS_Form_h8a1f5fd35db40729067e102073920ed.js
  studioactions/mobile/AS_Form_i11a3b0e862f4f5e88877ea0bc7a1e4f.js
  userwidgets/com.ita.components.HeaderControl/modules/require/HeaderControlController.js
Labels: ready for code review, ready for form review

#119 Rakhimova 118 click on image
  controllers/mobile/frmMovieDetailsController/frmMovieDetailsController.js
  controllers/mobile/frmPersonInfoController/frmPersonInfoController.js
  modules/require/MovieServiceFabricImpl.js
Labels: ready for code review

#120 Novikov 116 create btn show more
  controllers/mobile/frmMovieListController/frmMovieListController.js
  controllers/mobile/frmSearchController/frmSearchController.js
  forms/mobile/frmMovieList.sm/btnShowMore.json
  forms/mobile/frmMovieList.sm/flxListContainer.json
  forms/mobile/frmMovieList.sm/frmMovieList.json
  forms/mobile/frmMovieList.sm/lstMovies.json
  forms/mobile/frmSearch.sm/lstMovies.json
  modules/Constants.js
  modules/require/MovieServiceFabricImpl.js
  themes/defaultTheme/sknBtnFocusShowMore.json
  themes/defaultTheme/sknBtnShowMore.json
Labels: ready for code review, ready for form review

#123 Novikov 116 create btn show more
  .storyboard
  controllers/mobile/frmMovieDetailsController/frmMovieDetailsController.js
  controllers/mobile/frmMovieListController/frmMovieListController.js
  controllers/mobile/frmNearestCinemasController/frmNearestCinemasController.js
  controllers/mobile/frmProfileController/frmProfileController.js
  controllers/mobile/frmSearchController/frmSearchController.js
  forms/mobile/frmAuthentication.sm/.thumbs/default.jpeg
  forms/mobile/frmFavouriteList.sm/.thumbs/default.jpeg
  forms/mobile/frmMovieDetails.sm/.thumbs/default.jpeg
  forms/mobile/frmNearestCinemas.sm/.thumbs/default.jpeg
  forms/mobile/frmRegistration.sm/.thumbs/default.jpeg
  forms/mobile/frmSearch.sm/btnShowMore.json
  forms/mobile/frmSearch.sm/flxListContainer.json
  forms/mobile/frmSearch.sm/frmSearch.json
  forms/mobile/frmSearch.sm/lstMovies.json
  modules/Constants.js
  modules/require/MovieServiceFabricImpl.js
  themes/defaultTheme/sknBtnNavigateFocus.json
Labels: question, ready for code review

#125 Novikov fixes
  controllers/mobile/frmMovieListController/frmMovieListController.js
  controllers/mobile/frmSearchController/frmSearchController.js
  modules/MovieData.js
  modules/TvData.js
  modules/require/MovieServiceFabricImpl.js
Labels: ready for code review

#128 Rakhimova Log out functionality
  controllers/mobile/frmAuthenticationController/frmAuthenticationController.js
  controllers/mobile/frmFavouriteListController/frmFavouriteListController.js
  controllers/mobile/frmMovieDetailsController/frmMovieDetailsController.js
  controllers/mobile/frmPersonInfoController/frmPersonInfoController.js
  controllers/mobile/frmSearchController/frmSearchController.js
  forms/mobile/frmMovieList.sm/frmMovieList.json
  modules/Constants.js
  modules/CurrentSession.js
  modules/generalFunctions.js
  userwidgets/com.ita.components.HeaderControl/modules/require/HeaderControlController.js
Labels: ready for code review

#129 Final bug fix
  controllers/mobile/frmFavouriteListController/frmFavouriteListController.js
  controllers/mobile/frmMovieDetailsController/frmMovieDetailsController.js
  modules/MovieData.js
  modules/TvData.js
  modules/require/MovieServiceFabricImpl.js
Labels: ready for code review

#131 Final bug fix
  controllers/mobile/frmMovieDetailsController/frmMovieDetailsController.js
  controllers/mobile/frmMovieListController/frmMovieListController.js
  controllers/mobile/frmPersonInfoController/frmPersonInfoController.js
  controllers/mobile/frmSearchController/frmSearchController.js
  modules/CurrentSession.js
  modules/PersonInfo.js
  modules/require/MovieServiceFabricImpl.js
  resources/mobile/common/icons8_test_account_96.png
  resources/mobile/common/loader1.png
  resources/mobile/common/loader2.gif
  resources/mobile/common/loader_gif.gif
  resources/mobile/common/movie.png
  resources/mobile/common/person.png
  userwidgets/com.ita.components.MovieList/modules/require/MovieListController.js
Labels: ready for code review, ready for form review
